app:
    channel: test_kafka

channels:
    test_kafka:
        type: kafka
        params:
            producer_config:
                bootstrap-servers: maggie-kafka-1:9093
            consumer_config:
                bootstrap-servers: maggie-kafka-1:9093
            topics_mapping:
                bigbrother-test: (.*)