#---------------------
# configuration sample
#---------------------

channel:
    type: kafka
    params:
        producer_config:
            bootstrap_servers: ["maggie-kafka-1:9093"]
        consumer_config:
            bootstrap_servers: ["maggie-kafka-1:9093"]
        topics_mapping:
            bigbrother-test: [".*"]

# check logging module for more parameters
logging:
    level: DEBUG
    # filename:
    # format:
